site_name: Installing IBM Cloud Private
nav:
    - Home: index.md
    - Creating VMs: createvms.md
    - Setup on All VMs: setupall.md
    - Setup on Boot/Master/Proxy: master.md
    - Installation: installicp.md
    - Installing and Configuring LDAP: ldap.md

theme: readthedocs
markdown_extensions:
  - admonition