site_name: Installing IBM Cloud Private
repo_url: https://github.com/IBM-ICP-CoC/ICP-311-Install
edit_url: root/path/docs
nav:
    - Home: index.md
    - Creating VMs: createvms.md
    - Setup on All VMs: setupall.md
    - Installation: installicp.md
    - Using a custom URL: customurl.md
    - Installing and Configuring LDAP: ldap.md

theme: readthedocs
markdown_extensions:
  - admonition